CREATE TABLE users (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  age INT NOT NULL CHECK (age >= 0)
);

CREATE TABLE balances (
  user_id BIGINT NOT NULL UNIQUE REFERENCES users ON DELETE CASCADE,
  amount NUMERIC NOT NULL CHECK (amount >= 0)
);

CREATE TABLE transfers (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  amount NUMERIC NOT NULL CHECK (amount >= 0),
  from_user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
  to_user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE
);